openapi: 3.0.0
info:
  title: API de Sistema de Facturación y Stock
  description: API para gestionar facturas, productos, clientes, proveedores, inventario y reportes.
  version: 1.0.0
servers:
  - url: localhost:8080/par2025

paths:
  /facturas:
    get:
      tags:
        - Facturas
      summary: Obtener todas las facturas
      responses:
        '200':
          description: Lista de facturas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factura'
    post:
      tags:
        - Facturas
      summary: Crear una nueva factura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura actualizada correctamente
        '201':
          description: Factura creada correctamente
        '400':
          description: Datos de entrada no válidos
  /facturas/{id}:
    get:
      tags:
        - Facturas
      summary: Obtener una factura por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único de la factura
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Factura obtenida correctamente
        '404':
          description: Factura no encontrada
    put:
      tags:
        - Facturas
      summary: Actualizar una factura existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único de la factura a actualizar
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factura'
      responses:
        '200':
          description: Factura actualizada correctamente
        '404':
          description: Factura no encontrada
        '400':
          description: Datos de entrada no válidos
    delete:
      tags:
        - Facturas
      summary: Eliminar una factura existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único de la factura
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Factura eliminada correctamente
        '404':
          description: Factura no encontrada

  /productos:
    get:
      tags:
        - Productos
      summary: Obtener todos los productos en stock
      responses:
        '200':
          description: Lista de productos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Producto'
    post:
      tags:
        - Productos
      summary: Crear un nuevo producto en el stock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado correctamente
        '201':
          description: Producto creado correctamente
        '400':
          description: Datos de entrada no válidos
  /productos/{id}:
    put:
      tags:
        - Productos
      summary: Actualizar un producto existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del producto a actualizar
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado correctamente
        '404':
          description: Producto no encontrado
        '400':
          description: Datos de entrada no válidos
    delete:
      tags:
        - Productos
      summary: Eliminar un producto existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del producto a eliminar
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Producto eliminado correctamente
        '404':
          description: Producto no encontrado
  /clientes:
    get:
      tags:
        - Clientes
      summary: Obtener todos los clientes
      responses:
        '200':
          description: Lista de clientes obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cliente'
    post:
      tags:
        - Clientes
      summary: Crear un nuevo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Cliente actualizado correctamente
        '201':
          description: Cliente creado correctamente
        '400':
          description: Datos de entrada no válidos
  /clientes/{id}:
    get:
      tags:
        - Clientes
      summary: Obtener un cliente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Cliente obtenido correctamente
        '404':
          description: Cliente no encontrado
    put:
      tags:
        - Clientes
      summary: Actualizar los datos de un cliente existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente a actualizar
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
      responses:
        '200':
          description: Producto actualizado correctamente
        '404':
          description: Producto no encontrado
        '400':
          description: Datos de entrada no válidos
    delete:
      tags:
        - Clientes
      summary: Eliminar un cliente existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del cliente a eliminar
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Cliente eliminado correctamente
        '404':
          description: Cliente no encontrado
  /proveedores:
    get:
      tags:
        - Proveedores
      summary: Obtener todos los proveedores
      responses:
        '200':
          description: Lista de proveedores obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Proveedor'
    post:
      tags:
        - Proveedores
      summary: Crear un nuevo proveedor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proveedor'
      responses:
        '200':
          description: Proveedor actualizado correctamente
        '201':
          description: Proveedor creado correctamente
        '400':
          description: Datos de entrada no válidos
  /proveedores/{id}:
    get:
      tags:
        - Proveedores
      summary: Obtener un proveedor por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del proveedor
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Proveedor obtenido correctamente
        '404':
          description: Proveedor no encontrado
    put:
      tags:
        - Proveedores
      summary: Actualizar los datos de un proveedor existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del proveedor a actualizar
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proveedor'
      responses:
        '200':
          description: Proveedor actualizado correctamente
        '404':
          description: Proveedor no encontrado
        '400':
          description: Datos de entrada no válidos
    delete:
      tags:
        - Proveedores
      summary: Eliminar un proveedor existente por su ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID único del proveedor a eliminar
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Proveedor eliminado correctamente
        '404':
          description: Proveedor no encontrado
components:
  schemas:
    Factura:
      type: object
      properties:
        id:
          type: integer
          format: int64
        numero:
          type: string
        cliente:
          type: string
        total:
          type: number
          format: double
      required:
        - numero
        - cliente
        - total
    Producto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        precio:
          type: number
          format: double
        descripcion:
          type: string
      required:
        - nombre
        - precio
    Cliente:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        apellido:
          type: string
        ruc:
          type: string
        direccion:
          type: string
      required:
        - nombre
        - apellido
        - ruc
    Proveedor:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        ruc:
          type: string
        telefono:
          type: string
        email:
          type: string
          format: email
        direccion:
          type: string
      required:
        - nombre
        - telefono
        - ruc